"""Add order field to Member

Revision ID: 0f5e59690f20
Revises: c1f4c5686eaf
Create Date: 2025-07-18 02:12:07.928465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5e59690f20'
down_revision = 'c1f4c5686eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
