"""Add BankTransaction table changes

Revision ID: 53b527fc28b2
Revises: 53b6bc42ed68
Create Date: 2025-07-19 12:45:32.293439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b527fc28b2'
down_revision = '53b6bc42ed68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interest_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance_amount', sa.Float(), nullable=True))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('type')
        batch_op.drop_column('amount')
        batch_op.drop_column('balance_after')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('balance_amount')
        batch_op.drop_column('interest_amount')
        batch_op.drop_column('withdrawal_amount')

    # ### end Alembic commands ###
