"""Make payment  Guest

Revision ID: 782d32f678ff
Revises: d3e2dbe7eddc
Create Date: 2025-07-10 16:28:59.574055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782d32f678ff'
down_revision = 'd3e2dbe7eddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['bought_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bought_by_id')

    # ### end Alembic commands ###
