"""Add Chanda table

Revision ID: ac10f8424362
Revises: de5f8bcf86f4
Create Date: 2025-07-10 07:54:26.506722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac10f8424362'
down_revision = 'de5f8bcf86f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own_payment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('collected_amount', sa.Float(), nullable=False))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('collected_amount')
        batch_op.drop_column('own_payment')

    # ### end Alembic commands ###
