"""Make payment  Guest

Revision ID: d3e2dbe7eddc
Revises: bcdadaa8d6c1
Create Date: 2025-07-10 15:30:18.315987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e2dbe7eddc'
down_revision = 'bcdadaa8d6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('guest_event_id_fkey'), type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('guest_event_id_fkey'), 'event', ['event_id'], ['id'])

    op.drop_table('guest_payment')
    # ### end Alembic commands ###
